// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_service.proto

package com.rpc.service.web.searcher.searxng;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rpc.service.web.searcher.searxng.SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 搜索关键词, e.g., "苹果17"
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <pre>
   * 搜索关键词, e.g., "苹果17"
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <pre>
   * 页码
   * </pre>
   *
   * <code>int32 page_number = 2;</code>
   * @return The pageNumber.
   */
  int getPageNumber();

  /**
   * <pre>
   * 时间范围, e.g., "", "day", "week"
   * </pre>
   *
   * <code>string time_range = 3;</code>
   * @return The timeRange.
   */
  java.lang.String getTimeRange();
  /**
   * <pre>
   * 时间范围, e.g., "", "day", "week"
   * </pre>
   *
   * <code>string time_range = 3;</code>
   * @return The bytes for timeRange.
   */
  com.google.protobuf.ByteString
      getTimeRangeBytes();

  /**
   * <pre>
   * 类别, e.g., "general", "images"
   * </pre>
   *
   * <code>string category = 4;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <pre>
   * 类别, e.g., "general", "images"
   * </pre>
   *
   * <code>string category = 4;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <pre>
   * 语言, e.g., "auto", "zh-CN"
   * </pre>
   *
   * <code>string language = 5;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * 语言, e.g., "auto", "zh-CN"
   * </pre>
   *
   * <code>string language = 5;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <pre>
   * 安全搜索 (true for 1, false for 0)
   * </pre>
   *
   * <code>bool safe_search = 6;</code>
   * @return The safeSearch.
   */
  boolean getSafeSearch();
}
