// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_service.proto

package com.rpc.service.web.searcher.searxng;

/**
 * <pre>
 * 搜索请求消息，包含了所有用户指定的参数
 * </pre>
 *
 * Protobuf type {@code com.rpc.service.web.searcher.searxng.SearchRequest}
 */
public final class SearchRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.rpc.service.web.searcher.searxng.SearchRequest)
    SearchRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchRequest.newBuilder() to construct.
  private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchRequest() {
    query_ = "";
    timeRange_ = "";
    category_ = "";
    language_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rpc.service.web.searcher.searxng.SearXNGProto.internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rpc.service.web.searcher.searxng.SearXNGProto.internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rpc.service.web.searcher.searxng.SearchRequest.class, com.rpc.service.web.searcher.searxng.SearchRequest.Builder.class);
  }

  public static final int QUERY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object query_ = "";
  /**
   * <pre>
   * 搜索关键词, e.g., "苹果17"
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The query.
   */
  @java.lang.Override
  public java.lang.String getQuery() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      query_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 搜索关键词, e.g., "苹果17"
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueryBytes() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      query_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
  private int pageNumber_ = 0;
  /**
   * <pre>
   * 页码
   * </pre>
   *
   * <code>int32 page_number = 2;</code>
   * @return The pageNumber.
   */
  @java.lang.Override
  public int getPageNumber() {
    return pageNumber_;
  }

  public static final int TIME_RANGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timeRange_ = "";
  /**
   * <pre>
   * 时间范围, e.g., "", "day", "week"
   * </pre>
   *
   * <code>string time_range = 3;</code>
   * @return The timeRange.
   */
  @java.lang.Override
  public java.lang.String getTimeRange() {
    java.lang.Object ref = timeRange_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeRange_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 时间范围, e.g., "", "day", "week"
   * </pre>
   *
   * <code>string time_range = 3;</code>
   * @return The bytes for timeRange.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeRangeBytes() {
    java.lang.Object ref = timeRange_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeRange_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object category_ = "";
  /**
   * <pre>
   * 类别, e.g., "general", "images"
   * </pre>
   *
   * <code>string category = 4;</code>
   * @return The category.
   */
  @java.lang.Override
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 类别, e.g., "general", "images"
   * </pre>
   *
   * <code>string category = 4;</code>
   * @return The bytes for category.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object language_ = "";
  /**
   * <pre>
   * 语言, e.g., "auto", "zh-CN"
   * </pre>
   *
   * <code>string language = 5;</code>
   * @return The language.
   */
  @java.lang.Override
  public java.lang.String getLanguage() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      language_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 语言, e.g., "auto", "zh-CN"
   * </pre>
   *
   * <code>string language = 5;</code>
   * @return The bytes for language.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      language_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SAFE_SEARCH_FIELD_NUMBER = 6;
  private boolean safeSearch_ = false;
  /**
   * <pre>
   * 安全搜索 (true for 1, false for 0)
   * </pre>
   *
   * <code>bool safe_search = 6;</code>
   * @return The safeSearch.
   */
  @java.lang.Override
  public boolean getSafeSearch() {
    return safeSearch_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
    }
    if (pageNumber_ != 0) {
      output.writeInt32(2, pageNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeRange_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timeRange_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(category_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, category_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, language_);
    }
    if (safeSearch_ != false) {
      output.writeBool(6, safeSearch_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
    }
    if (pageNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, pageNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeRange_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timeRange_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(category_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, category_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, language_);
    }
    if (safeSearch_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, safeSearch_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rpc.service.web.searcher.searxng.SearchRequest)) {
      return super.equals(obj);
    }
    com.rpc.service.web.searcher.searxng.SearchRequest other = (com.rpc.service.web.searcher.searxng.SearchRequest) obj;

    if (!getQuery()
        .equals(other.getQuery())) return false;
    if (getPageNumber()
        != other.getPageNumber()) return false;
    if (!getTimeRange()
        .equals(other.getTimeRange())) return false;
    if (!getCategory()
        .equals(other.getCategory())) return false;
    if (!getLanguage()
        .equals(other.getLanguage())) return false;
    if (getSafeSearch()
        != other.getSafeSearch()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUERY_FIELD_NUMBER;
    hash = (53 * hash) + getQuery().hashCode();
    hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPageNumber();
    hash = (37 * hash) + TIME_RANGE_FIELD_NUMBER;
    hash = (53 * hash) + getTimeRange().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguage().hashCode();
    hash = (37 * hash) + SAFE_SEARCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSafeSearch());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rpc.service.web.searcher.searxng.SearchRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rpc.service.web.searcher.searxng.SearchRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.searcher.searxng.SearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rpc.service.web.searcher.searxng.SearchRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 搜索请求消息，包含了所有用户指定的参数
   * </pre>
   *
   * Protobuf type {@code com.rpc.service.web.searcher.searxng.SearchRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.rpc.service.web.searcher.searxng.SearchRequest)
      com.rpc.service.web.searcher.searxng.SearchRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rpc.service.web.searcher.searxng.SearXNGProto.internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rpc.service.web.searcher.searxng.SearXNGProto.internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rpc.service.web.searcher.searxng.SearchRequest.class, com.rpc.service.web.searcher.searxng.SearchRequest.Builder.class);
    }

    // Construct using com.rpc.service.web.searcher.searxng.SearchRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      query_ = "";
      pageNumber_ = 0;
      timeRange_ = "";
      category_ = "";
      language_ = "";
      safeSearch_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rpc.service.web.searcher.searxng.SearXNGProto.internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_descriptor;
    }

    @java.lang.Override
    public com.rpc.service.web.searcher.searxng.SearchRequest getDefaultInstanceForType() {
      return com.rpc.service.web.searcher.searxng.SearchRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.rpc.service.web.searcher.searxng.SearchRequest build() {
      com.rpc.service.web.searcher.searxng.SearchRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rpc.service.web.searcher.searxng.SearchRequest buildPartial() {
      com.rpc.service.web.searcher.searxng.SearchRequest result = new com.rpc.service.web.searcher.searxng.SearchRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rpc.service.web.searcher.searxng.SearchRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.query_ = query_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pageNumber_ = pageNumber_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timeRange_ = timeRange_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.category_ = category_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.language_ = language_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.safeSearch_ = safeSearch_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rpc.service.web.searcher.searxng.SearchRequest) {
        return mergeFrom((com.rpc.service.web.searcher.searxng.SearchRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rpc.service.web.searcher.searxng.SearchRequest other) {
      if (other == com.rpc.service.web.searcher.searxng.SearchRequest.getDefaultInstance()) return this;
      if (!other.getQuery().isEmpty()) {
        query_ = other.query_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getPageNumber() != 0) {
        setPageNumber(other.getPageNumber());
      }
      if (!other.getTimeRange().isEmpty()) {
        timeRange_ = other.timeRange_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getLanguage().isEmpty()) {
        language_ = other.language_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getSafeSearch() != false) {
        setSafeSearch(other.getSafeSearch());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              query_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              pageNumber_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              timeRange_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              category_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              language_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              safeSearch_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object query_ = "";
    /**
     * <pre>
     * 搜索关键词, e.g., "苹果17"
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The query.
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 搜索关键词, e.g., "苹果17"
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 搜索关键词, e.g., "苹果17"
     * </pre>
     *
     * <code>string query = 1;</code>
     * @param value The query to set.
     * @return This builder for chaining.
     */
    public Builder setQuery(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      query_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搜索关键词, e.g., "苹果17"
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuery() {
      query_ = getDefaultInstance().getQuery();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搜索关键词, e.g., "苹果17"
     * </pre>
     *
     * <code>string query = 1;</code>
     * @param value The bytes for query to set.
     * @return This builder for chaining.
     */
    public Builder setQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      query_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int pageNumber_ ;
    /**
     * <pre>
     * 页码
     * </pre>
     *
     * <code>int32 page_number = 2;</code>
     * @return The pageNumber.
     */
    @java.lang.Override
    public int getPageNumber() {
      return pageNumber_;
    }
    /**
     * <pre>
     * 页码
     * </pre>
     *
     * <code>int32 page_number = 2;</code>
     * @param value The pageNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPageNumber(int value) {

      pageNumber_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页码
     * </pre>
     *
     * <code>int32 page_number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pageNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object timeRange_ = "";
    /**
     * <pre>
     * 时间范围, e.g., "", "day", "week"
     * </pre>
     *
     * <code>string time_range = 3;</code>
     * @return The timeRange.
     */
    public java.lang.String getTimeRange() {
      java.lang.Object ref = timeRange_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeRange_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 时间范围, e.g., "", "day", "week"
     * </pre>
     *
     * <code>string time_range = 3;</code>
     * @return The bytes for timeRange.
     */
    public com.google.protobuf.ByteString
        getTimeRangeBytes() {
      java.lang.Object ref = timeRange_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeRange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 时间范围, e.g., "", "day", "week"
     * </pre>
     *
     * <code>string time_range = 3;</code>
     * @param value The timeRange to set.
     * @return This builder for chaining.
     */
    public Builder setTimeRange(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timeRange_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间范围, e.g., "", "day", "week"
     * </pre>
     *
     * <code>string time_range = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeRange() {
      timeRange_ = getDefaultInstance().getTimeRange();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间范围, e.g., "", "day", "week"
     * </pre>
     *
     * <code>string time_range = 3;</code>
     * @param value The bytes for timeRange to set.
     * @return This builder for chaining.
     */
    public Builder setTimeRangeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timeRange_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <pre>
     * 类别, e.g., "general", "images"
     * </pre>
     *
     * <code>string category = 4;</code>
     * @return The category.
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 类别, e.g., "general", "images"
     * </pre>
     *
     * <code>string category = 4;</code>
     * @return The bytes for category.
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 类别, e.g., "general", "images"
     * </pre>
     *
     * <code>string category = 4;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      category_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 类别, e.g., "general", "images"
     * </pre>
     *
     * <code>string category = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      category_ = getDefaultInstance().getCategory();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 类别, e.g., "general", "images"
     * </pre>
     *
     * <code>string category = 4;</code>
     * @param value The bytes for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      category_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object language_ = "";
    /**
     * <pre>
     * 语言, e.g., "auto", "zh-CN"
     * </pre>
     *
     * <code>string language = 5;</code>
     * @return The language.
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 语言, e.g., "auto", "zh-CN"
     * </pre>
     *
     * <code>string language = 5;</code>
     * @return The bytes for language.
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 语言, e.g., "auto", "zh-CN"
     * </pre>
     *
     * <code>string language = 5;</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      language_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 语言, e.g., "auto", "zh-CN"
     * </pre>
     *
     * <code>string language = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      language_ = getDefaultInstance().getLanguage();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 语言, e.g., "auto", "zh-CN"
     * </pre>
     *
     * <code>string language = 5;</code>
     * @param value The bytes for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      language_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private boolean safeSearch_ ;
    /**
     * <pre>
     * 安全搜索 (true for 1, false for 0)
     * </pre>
     *
     * <code>bool safe_search = 6;</code>
     * @return The safeSearch.
     */
    @java.lang.Override
    public boolean getSafeSearch() {
      return safeSearch_;
    }
    /**
     * <pre>
     * 安全搜索 (true for 1, false for 0)
     * </pre>
     *
     * <code>bool safe_search = 6;</code>
     * @param value The safeSearch to set.
     * @return This builder for chaining.
     */
    public Builder setSafeSearch(boolean value) {

      safeSearch_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 安全搜索 (true for 1, false for 0)
     * </pre>
     *
     * <code>bool safe_search = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSafeSearch() {
      bitField0_ = (bitField0_ & ~0x00000020);
      safeSearch_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.rpc.service.web.searcher.searxng.SearchRequest)
  }

  // @@protoc_insertion_point(class_scope:com.rpc.service.web.searcher.searxng.SearchRequest)
  private static final com.rpc.service.web.searcher.searxng.SearchRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rpc.service.web.searcher.searxng.SearchRequest();
  }

  public static com.rpc.service.web.searcher.searxng.SearchRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchRequest>
      PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
    @java.lang.Override
    public SearchRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SearchRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rpc.service.web.searcher.searxng.SearchRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

