// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_service.proto

package com.rpc.service.web.searcher.searxng;

public interface SearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rpc.service.web.searcher.searxng.SearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.rpc.service.web.searcher.searxng.SearchResultItem results = 1;</code>
   */
  java.util.List<com.rpc.service.web.searcher.searxng.SearchResultItem> 
      getResultsList();
  /**
   * <code>repeated .com.rpc.service.web.searcher.searxng.SearchResultItem results = 1;</code>
   */
  com.rpc.service.web.searcher.searxng.SearchResultItem getResults(int index);
  /**
   * <code>repeated .com.rpc.service.web.searcher.searxng.SearchResultItem results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .com.rpc.service.web.searcher.searxng.SearchResultItem results = 1;</code>
   */
  java.util.List<? extends com.rpc.service.web.searcher.searxng.SearchResultItemOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .com.rpc.service.web.searcher.searxng.SearchResultItem results = 1;</code>
   */
  com.rpc.service.web.searcher.searxng.SearchResultItemOrBuilder getResultsOrBuilder(
      int index);
}
