// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_service.proto

package com.rpc.service.web.searcher.searxng;

public final class SearXNGProto {
  private SearXNGProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_searcher_searxng_SearchResultItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_searcher_searxng_SearchResultItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_searcher_searxng_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_searcher_searxng_SearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024search_service.proto\022$com.rpc.service." +
      "web.searcher.searxng\"\200\001\n\rSearchRequest\022\r" +
      "\n\005query\030\001 \001(\t\022\023\n\013page_number\030\002 \001(\005\022\022\n\nti" +
      "me_range\030\003 \001(\t\022\020\n\010category\030\004 \001(\t\022\020\n\010lang" +
      "uage\030\005 \001(\t\022\023\n\013safe_search\030\006 \001(\010\"?\n\020Searc" +
      "hResultItem\022\r\n\005title\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022" +
      "\017\n\007content\030\003 \001(\t\"Y\n\016SearchResponse\022G\n\007re" +
      "sults\030\001 \003(\01326.com.rpc.service.web.search" +
      "er.searxng.SearchResultItem2\211\001\n\022AsyncSea" +
      "rchService\022s\n\006Search\0223.com.rpc.service.w" +
      "eb.searcher.searxng.SearchRequest\0324.com." +
      "rpc.service.web.searcher.searxng.SearchR" +
      "esponseB6\n$com.rpc.service.web.searcher." +
      "searxngB\014SearXNGProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_searcher_searxng_SearchRequest_descriptor,
        new java.lang.String[] { "Query", "PageNumber", "TimeRange", "Category", "Language", "SafeSearch", });
    internal_static_com_rpc_service_web_searcher_searxng_SearchResultItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_rpc_service_web_searcher_searxng_SearchResultItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_searcher_searxng_SearchResultItem_descriptor,
        new java.lang.String[] { "Title", "Url", "Content", });
    internal_static_com_rpc_service_web_searcher_searxng_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_rpc_service_web_searcher_searxng_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_searcher_searxng_SearchResponse_descriptor,
        new java.lang.String[] { "Results", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
