// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_viewer.proto

package com.rpc.service.web.viewer.selectolax;

public final class SelectolaxProto {
  private SelectolaxProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_CustomHeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_CustomHeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020web_viewer.proto\022%com.rpc.service.web." +
      "viewer.selectolax\032\037google/protobuf/times" +
      "tamp.proto\"\356\002\n\013ViewRequest\022\013\n\003url\030\001 \001(\t\022" +
      "\027\n\017timeout_seconds\030\002 \001(\005\022]\n\016custom_heade" +
      "rs\030\003 \003(\0132E.com.rpc.service.web.viewer.se" +
      "lectolax.ViewRequest.CustomHeadersEntry\022" +
      "\025\n\rinclude_links\030\004 \001(\010\022\026\n\016include_images" +
      "\030\005 \001(\010\022\031\n\021preserve_newlines\030\006 \001(\010\022\033\n\016tex" +
      "t_start_pos\030\007 \001(\005H\000\210\001\001\022\031\n\014text_end_pos\030\010" +
      " \001(\005H\001\210\001\001\0324\n\022CustomHeadersEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\021\n\017_text_start_p" +
      "osB\017\n\r_text_end_pos\"\323\001\n\014ViewResponse\022\013\n\003" +
      "url\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\024\n\014text_content" +
      "\030\003 \001(\t\022\r\n\005links\030\004 \003(\t\022\016\n\006images\030\005 \003(\t\022\023\n" +
      "\013status_code\030\006 \001(\005\022-\n\tviewed_at\030\007 \001(\0132\032." +
      "google.protobuf.Timestamp\022\025\n\rerror_messa" +
      "ge\030\010 \001(\t\022\027\n\017processing_time\030\t \001(\0012\212\001\n\020We" +
      "bViewerService\022v\n\013ViewWebPage\0222.com.rpc." +
      "service.web.viewer.selectolax.ViewReques" +
      "t\0323.com.rpc.service.web.viewer.selectola" +
      "x.ViewResponseB:\n%com.rpc.service.web.vi" +
      "ewer.selectolaxB\017SelectolaxProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_descriptor,
        new java.lang.String[] { "Url", "TimeoutSeconds", "CustomHeaders", "IncludeLinks", "IncludeImages", "PreserveNewlines", "TextStartPos", "TextEndPos", "TextStartPos", "TextEndPos", });
    internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_CustomHeadersEntry_descriptor =
      internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_CustomHeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_CustomHeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_descriptor,
        new java.lang.String[] { "Url", "Title", "TextContent", "Links", "Images", "StatusCode", "ViewedAt", "ErrorMessage", "ProcessingTime", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
