// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_viewer.proto

package com.rpc.service.web.viewer.selectolax;

/**
 * <pre>
 * 浏览响应
 * </pre>
 *
 * Protobuf type {@code com.rpc.service.web.viewer.selectolax.ViewResponse}
 */
public final class ViewResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.rpc.service.web.viewer.selectolax.ViewResponse)
    ViewResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ViewResponse.newBuilder() to construct.
  private ViewResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ViewResponse() {
    url_ = "";
    title_ = "";
    textContent_ = "";
    links_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    images_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    errorMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ViewResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rpc.service.web.viewer.selectolax.ViewResponse.class, com.rpc.service.web.viewer.selectolax.ViewResponse.Builder.class);
  }

  public static final int URL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object url_ = "";
  /**
   * <pre>
   * 原始URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 原始URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <pre>
   * 页面标题
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 页面标题
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEXT_CONTENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object textContent_ = "";
  /**
   * <pre>
   * 提取的文本内容
   * </pre>
   *
   * <code>string text_content = 3;</code>
   * @return The textContent.
   */
  @java.lang.Override
  public java.lang.String getTextContent() {
    java.lang.Object ref = textContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      textContent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 提取的文本内容
   * </pre>
   *
   * <code>string text_content = 3;</code>
   * @return The bytes for textContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextContentBytes() {
    java.lang.Object ref = textContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      textContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LINKS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList links_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 页面中的链接
   * </pre>
   *
   * <code>repeated string links = 4;</code>
   * @return A list containing the links.
   */
  public com.google.protobuf.ProtocolStringList
      getLinksList() {
    return links_;
  }
  /**
   * <pre>
   * 页面中的链接
   * </pre>
   *
   * <code>repeated string links = 4;</code>
   * @return The count of links.
   */
  public int getLinksCount() {
    return links_.size();
  }
  /**
   * <pre>
   * 页面中的链接
   * </pre>
   *
   * <code>repeated string links = 4;</code>
   * @param index The index of the element to return.
   * @return The links at the given index.
   */
  public java.lang.String getLinks(int index) {
    return links_.get(index);
  }
  /**
   * <pre>
   * 页面中的链接
   * </pre>
   *
   * <code>repeated string links = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the links at the given index.
   */
  public com.google.protobuf.ByteString
      getLinksBytes(int index) {
    return links_.getByteString(index);
  }

  public static final int IMAGES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList images_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 页面中的图片URL
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @return A list containing the images.
   */
  public com.google.protobuf.ProtocolStringList
      getImagesList() {
    return images_;
  }
  /**
   * <pre>
   * 页面中的图片URL
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @return The count of images.
   */
  public int getImagesCount() {
    return images_.size();
  }
  /**
   * <pre>
   * 页面中的图片URL
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @param index The index of the element to return.
   * @return The images at the given index.
   */
  public java.lang.String getImages(int index) {
    return images_.get(index);
  }
  /**
   * <pre>
   * 页面中的图片URL
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the images at the given index.
   */
  public com.google.protobuf.ByteString
      getImagesBytes(int index) {
    return images_.getByteString(index);
  }

  public static final int STATUS_CODE_FIELD_NUMBER = 6;
  private int statusCode_ = 0;
  /**
   * <pre>
   * HTTP状态码
   * </pre>
   *
   * <code>int32 status_code = 6;</code>
   * @return The statusCode.
   */
  @java.lang.Override
  public int getStatusCode() {
    return statusCode_;
  }

  public static final int VIEWED_AT_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp viewedAt_;
  /**
   * <pre>
   * 浏览时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
   * @return Whether the viewedAt field is set.
   */
  @java.lang.Override
  public boolean hasViewedAt() {
    return viewedAt_ != null;
  }
  /**
   * <pre>
   * 浏览时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
   * @return The viewedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getViewedAt() {
    return viewedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : viewedAt_;
  }
  /**
   * <pre>
   * 浏览时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getViewedAtOrBuilder() {
    return viewedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : viewedAt_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <pre>
   * 错误信息（如果有）
   * </pre>
   *
   * <code>string error_message = 8;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 错误信息（如果有）
   * </pre>
   *
   * <code>string error_message = 8;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCESSING_TIME_FIELD_NUMBER = 9;
  private double processingTime_ = 0D;
  /**
   * <pre>
   * 处理时间（秒）
   * </pre>
   *
   * <code>double processing_time = 9;</code>
   * @return The processingTime.
   */
  @java.lang.Override
  public double getProcessingTime() {
    return processingTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(textContent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, textContent_);
    }
    for (int i = 0; i < links_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, links_.getRaw(i));
    }
    for (int i = 0; i < images_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, images_.getRaw(i));
    }
    if (statusCode_ != 0) {
      output.writeInt32(6, statusCode_);
    }
    if (viewedAt_ != null) {
      output.writeMessage(7, getViewedAt());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, errorMessage_);
    }
    if (java.lang.Double.doubleToRawLongBits(processingTime_) != 0) {
      output.writeDouble(9, processingTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(textContent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, textContent_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < links_.size(); i++) {
        dataSize += computeStringSizeNoTag(links_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLinksList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < images_.size(); i++) {
        dataSize += computeStringSizeNoTag(images_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getImagesList().size();
    }
    if (statusCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, statusCode_);
    }
    if (viewedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getViewedAt());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, errorMessage_);
    }
    if (java.lang.Double.doubleToRawLongBits(processingTime_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, processingTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rpc.service.web.viewer.selectolax.ViewResponse)) {
      return super.equals(obj);
    }
    com.rpc.service.web.viewer.selectolax.ViewResponse other = (com.rpc.service.web.viewer.selectolax.ViewResponse) obj;

    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getTextContent()
        .equals(other.getTextContent())) return false;
    if (!getLinksList()
        .equals(other.getLinksList())) return false;
    if (!getImagesList()
        .equals(other.getImagesList())) return false;
    if (getStatusCode()
        != other.getStatusCode()) return false;
    if (hasViewedAt() != other.hasViewedAt()) return false;
    if (hasViewedAt()) {
      if (!getViewedAt()
          .equals(other.getViewedAt())) return false;
    }
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (java.lang.Double.doubleToLongBits(getProcessingTime())
        != java.lang.Double.doubleToLongBits(
            other.getProcessingTime())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + TEXT_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getTextContent().hashCode();
    if (getLinksCount() > 0) {
      hash = (37 * hash) + LINKS_FIELD_NUMBER;
      hash = (53 * hash) + getLinksList().hashCode();
    }
    if (getImagesCount() > 0) {
      hash = (37 * hash) + IMAGES_FIELD_NUMBER;
      hash = (53 * hash) + getImagesList().hashCode();
    }
    hash = (37 * hash) + STATUS_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getStatusCode();
    if (hasViewedAt()) {
      hash = (37 * hash) + VIEWED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getViewedAt().hashCode();
    }
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (37 * hash) + PROCESSING_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getProcessingTime()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rpc.service.web.viewer.selectolax.ViewResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 浏览响应
   * </pre>
   *
   * Protobuf type {@code com.rpc.service.web.viewer.selectolax.ViewResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.rpc.service.web.viewer.selectolax.ViewResponse)
      com.rpc.service.web.viewer.selectolax.ViewResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rpc.service.web.viewer.selectolax.ViewResponse.class, com.rpc.service.web.viewer.selectolax.ViewResponse.Builder.class);
    }

    // Construct using com.rpc.service.web.viewer.selectolax.ViewResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      url_ = "";
      title_ = "";
      textContent_ = "";
      links_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      images_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      statusCode_ = 0;
      viewedAt_ = null;
      if (viewedAtBuilder_ != null) {
        viewedAtBuilder_.dispose();
        viewedAtBuilder_ = null;
      }
      errorMessage_ = "";
      processingTime_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewResponse_descriptor;
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.selectolax.ViewResponse getDefaultInstanceForType() {
      return com.rpc.service.web.viewer.selectolax.ViewResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.selectolax.ViewResponse build() {
      com.rpc.service.web.viewer.selectolax.ViewResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.selectolax.ViewResponse buildPartial() {
      com.rpc.service.web.viewer.selectolax.ViewResponse result = new com.rpc.service.web.viewer.selectolax.ViewResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rpc.service.web.viewer.selectolax.ViewResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.url_ = url_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.textContent_ = textContent_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        links_.makeImmutable();
        result.links_ = links_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        images_.makeImmutable();
        result.images_ = images_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.statusCode_ = statusCode_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.viewedAt_ = viewedAtBuilder_ == null
            ? viewedAt_
            : viewedAtBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.processingTime_ = processingTime_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rpc.service.web.viewer.selectolax.ViewResponse) {
        return mergeFrom((com.rpc.service.web.viewer.selectolax.ViewResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rpc.service.web.viewer.selectolax.ViewResponse other) {
      if (other == com.rpc.service.web.viewer.selectolax.ViewResponse.getDefaultInstance()) return this;
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTextContent().isEmpty()) {
        textContent_ = other.textContent_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.links_.isEmpty()) {
        if (links_.isEmpty()) {
          links_ = other.links_;
          bitField0_ |= 0x00000008;
        } else {
          ensureLinksIsMutable();
          links_.addAll(other.links_);
        }
        onChanged();
      }
      if (!other.images_.isEmpty()) {
        if (images_.isEmpty()) {
          images_ = other.images_;
          bitField0_ |= 0x00000010;
        } else {
          ensureImagesIsMutable();
          images_.addAll(other.images_);
        }
        onChanged();
      }
      if (other.getStatusCode() != 0) {
        setStatusCode(other.getStatusCode());
      }
      if (other.hasViewedAt()) {
        mergeViewedAt(other.getViewedAt());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getProcessingTime() != 0D) {
        setProcessingTime(other.getProcessingTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              url_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              textContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureLinksIsMutable();
              links_.add(s);
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureImagesIsMutable();
              images_.add(s);
              break;
            } // case 42
            case 48: {
              statusCode_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              input.readMessage(
                  getViewedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 73: {
              processingTime_ = input.readDouble();
              bitField0_ |= 0x00000100;
              break;
            } // case 73
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object url_ = "";
    /**
     * <pre>
     * 原始URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 原始URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 原始URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      url_ = getDefaultInstance().getUrl();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <pre>
     * 页面标题
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 页面标题
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 页面标题
     * </pre>
     *
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面标题
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面标题
     * </pre>
     *
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object textContent_ = "";
    /**
     * <pre>
     * 提取的文本内容
     * </pre>
     *
     * <code>string text_content = 3;</code>
     * @return The textContent.
     */
    public java.lang.String getTextContent() {
      java.lang.Object ref = textContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        textContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 提取的文本内容
     * </pre>
     *
     * <code>string text_content = 3;</code>
     * @return The bytes for textContent.
     */
    public com.google.protobuf.ByteString
        getTextContentBytes() {
      java.lang.Object ref = textContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 提取的文本内容
     * </pre>
     *
     * <code>string text_content = 3;</code>
     * @param value The textContent to set.
     * @return This builder for chaining.
     */
    public Builder setTextContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      textContent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 提取的文本内容
     * </pre>
     *
     * <code>string text_content = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextContent() {
      textContent_ = getDefaultInstance().getTextContent();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 提取的文本内容
     * </pre>
     *
     * <code>string text_content = 3;</code>
     * @param value The bytes for textContent to set.
     * @return This builder for chaining.
     */
    public Builder setTextContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      textContent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList links_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureLinksIsMutable() {
      if (!links_.isModifiable()) {
        links_ = new com.google.protobuf.LazyStringArrayList(links_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * 页面中的链接
     * </pre>
     *
     * <code>repeated string links = 4;</code>
     * @return A list containing the links.
     */
    public com.google.protobuf.ProtocolStringList
        getLinksList() {
      links_.makeImmutable();
      return links_;
    }
    /**
     * <pre>
     * 页面中的链接
     * </pre>
     *
     * <code>repeated string links = 4;</code>
     * @return The count of links.
     */
    public int getLinksCount() {
      return links_.size();
    }
    /**
     * <pre>
     * 页面中的链接
     * </pre>
     *
     * <code>repeated string links = 4;</code>
     * @param index The index of the element to return.
     * @return The links at the given index.
     */
    public java.lang.String getLinks(int index) {
      return links_.get(index);
    }
    /**
     * <pre>
     * 页面中的链接
     * </pre>
     *
     * <code>repeated string links = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the links at the given index.
     */
    public com.google.protobuf.ByteString
        getLinksBytes(int index) {
      return links_.getByteString(index);
    }
    /**
     * <pre>
     * 页面中的链接
     * </pre>
     *
     * <code>repeated string links = 4;</code>
     * @param index The index to set the value at.
     * @param value The links to set.
     * @return This builder for chaining.
     */
    public Builder setLinks(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinksIsMutable();
      links_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面中的链接
     * </pre>
     *
     * <code>repeated string links = 4;</code>
     * @param value The links to add.
     * @return This builder for chaining.
     */
    public Builder addLinks(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinksIsMutable();
      links_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面中的链接
     * </pre>
     *
     * <code>repeated string links = 4;</code>
     * @param values The links to add.
     * @return This builder for chaining.
     */
    public Builder addAllLinks(
        java.lang.Iterable<java.lang.String> values) {
      ensureLinksIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, links_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面中的链接
     * </pre>
     *
     * <code>repeated string links = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinks() {
      links_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面中的链接
     * </pre>
     *
     * <code>repeated string links = 4;</code>
     * @param value The bytes of the links to add.
     * @return This builder for chaining.
     */
    public Builder addLinksBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLinksIsMutable();
      links_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList images_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureImagesIsMutable() {
      if (!images_.isModifiable()) {
        images_ = new com.google.protobuf.LazyStringArrayList(images_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * 页面中的图片URL
     * </pre>
     *
     * <code>repeated string images = 5;</code>
     * @return A list containing the images.
     */
    public com.google.protobuf.ProtocolStringList
        getImagesList() {
      images_.makeImmutable();
      return images_;
    }
    /**
     * <pre>
     * 页面中的图片URL
     * </pre>
     *
     * <code>repeated string images = 5;</code>
     * @return The count of images.
     */
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <pre>
     * 页面中的图片URL
     * </pre>
     *
     * <code>repeated string images = 5;</code>
     * @param index The index of the element to return.
     * @return The images at the given index.
     */
    public java.lang.String getImages(int index) {
      return images_.get(index);
    }
    /**
     * <pre>
     * 页面中的图片URL
     * </pre>
     *
     * <code>repeated string images = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the images at the given index.
     */
    public com.google.protobuf.ByteString
        getImagesBytes(int index) {
      return images_.getByteString(index);
    }
    /**
     * <pre>
     * 页面中的图片URL
     * </pre>
     *
     * <code>repeated string images = 5;</code>
     * @param index The index to set the value at.
     * @param value The images to set.
     * @return This builder for chaining.
     */
    public Builder setImages(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureImagesIsMutable();
      images_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面中的图片URL
     * </pre>
     *
     * <code>repeated string images = 5;</code>
     * @param value The images to add.
     * @return This builder for chaining.
     */
    public Builder addImages(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureImagesIsMutable();
      images_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面中的图片URL
     * </pre>
     *
     * <code>repeated string images = 5;</code>
     * @param values The images to add.
     * @return This builder for chaining.
     */
    public Builder addAllImages(
        java.lang.Iterable<java.lang.String> values) {
      ensureImagesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, images_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面中的图片URL
     * </pre>
     *
     * <code>repeated string images = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearImages() {
      images_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 页面中的图片URL
     * </pre>
     *
     * <code>repeated string images = 5;</code>
     * @param value The bytes of the images to add.
     * @return This builder for chaining.
     */
    public Builder addImagesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureImagesIsMutable();
      images_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int statusCode_ ;
    /**
     * <pre>
     * HTTP状态码
     * </pre>
     *
     * <code>int32 status_code = 6;</code>
     * @return The statusCode.
     */
    @java.lang.Override
    public int getStatusCode() {
      return statusCode_;
    }
    /**
     * <pre>
     * HTTP状态码
     * </pre>
     *
     * <code>int32 status_code = 6;</code>
     * @param value The statusCode to set.
     * @return This builder for chaining.
     */
    public Builder setStatusCode(int value) {

      statusCode_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * HTTP状态码
     * </pre>
     *
     * <code>int32 status_code = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusCode() {
      bitField0_ = (bitField0_ & ~0x00000020);
      statusCode_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp viewedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> viewedAtBuilder_;
    /**
     * <pre>
     * 浏览时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
     * @return Whether the viewedAt field is set.
     */
    public boolean hasViewedAt() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 浏览时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
     * @return The viewedAt.
     */
    public com.google.protobuf.Timestamp getViewedAt() {
      if (viewedAtBuilder_ == null) {
        return viewedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : viewedAt_;
      } else {
        return viewedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 浏览时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
     */
    public Builder setViewedAt(com.google.protobuf.Timestamp value) {
      if (viewedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        viewedAt_ = value;
      } else {
        viewedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浏览时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
     */
    public Builder setViewedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (viewedAtBuilder_ == null) {
        viewedAt_ = builderForValue.build();
      } else {
        viewedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浏览时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
     */
    public Builder mergeViewedAt(com.google.protobuf.Timestamp value) {
      if (viewedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          viewedAt_ != null &&
          viewedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getViewedAtBuilder().mergeFrom(value);
        } else {
          viewedAt_ = value;
        }
      } else {
        viewedAtBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浏览时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
     */
    public Builder clearViewedAt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      viewedAt_ = null;
      if (viewedAtBuilder_ != null) {
        viewedAtBuilder_.dispose();
        viewedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浏览时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getViewedAtBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getViewedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 浏览时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getViewedAtOrBuilder() {
      if (viewedAtBuilder_ != null) {
        return viewedAtBuilder_.getMessageOrBuilder();
      } else {
        return viewedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : viewedAt_;
      }
    }
    /**
     * <pre>
     * 浏览时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getViewedAtFieldBuilder() {
      if (viewedAtBuilder_ == null) {
        viewedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getViewedAt(),
                getParentForChildren(),
                isClean());
        viewedAt_ = null;
      }
      return viewedAtBuilder_;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <pre>
     * 错误信息（如果有）
     * </pre>
     *
     * <code>string error_message = 8;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 错误信息（如果有）
     * </pre>
     *
     * <code>string error_message = 8;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 错误信息（如果有）
     * </pre>
     *
     * <code>string error_message = 8;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息（如果有）
     * </pre>
     *
     * <code>string error_message = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息（如果有）
     * </pre>
     *
     * <code>string error_message = 8;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private double processingTime_ ;
    /**
     * <pre>
     * 处理时间（秒）
     * </pre>
     *
     * <code>double processing_time = 9;</code>
     * @return The processingTime.
     */
    @java.lang.Override
    public double getProcessingTime() {
      return processingTime_;
    }
    /**
     * <pre>
     * 处理时间（秒）
     * </pre>
     *
     * <code>double processing_time = 9;</code>
     * @param value The processingTime to set.
     * @return This builder for chaining.
     */
    public Builder setProcessingTime(double value) {

      processingTime_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 处理时间（秒）
     * </pre>
     *
     * <code>double processing_time = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessingTime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      processingTime_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.rpc.service.web.viewer.selectolax.ViewResponse)
  }

  // @@protoc_insertion_point(class_scope:com.rpc.service.web.viewer.selectolax.ViewResponse)
  private static final com.rpc.service.web.viewer.selectolax.ViewResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rpc.service.web.viewer.selectolax.ViewResponse();
  }

  public static com.rpc.service.web.viewer.selectolax.ViewResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ViewResponse>
      PARSER = new com.google.protobuf.AbstractParser<ViewResponse>() {
    @java.lang.Override
    public ViewResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ViewResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ViewResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rpc.service.web.viewer.selectolax.ViewResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

