// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_viewer.proto

package com.rpc.service.web.viewer.selectolax;

public interface ViewRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rpc.service.web.viewer.selectolax.ViewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 要浏览的网页URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * 要浏览的网页URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * 请求超时时间（秒），默认15秒
   * </pre>
   *
   * <code>int32 timeout_seconds = 2;</code>
   * @return The timeoutSeconds.
   */
  int getTimeoutSeconds();

  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  int getCustomHeadersCount();
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  boolean containsCustomHeaders(
      java.lang.String key);
  /**
   * Use {@link #getCustomHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getCustomHeaders();
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getCustomHeadersMap();
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  /* nullable */
java.lang.String getCustomHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  java.lang.String getCustomHeadersOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * 是否包含链接
   * </pre>
   *
   * <code>bool include_links = 4;</code>
   * @return The includeLinks.
   */
  boolean getIncludeLinks();

  /**
   * <pre>
   * 是否包含图片信息
   * </pre>
   *
   * <code>bool include_images = 5;</code>
   * @return The includeImages.
   */
  boolean getIncludeImages();

  /**
   * <pre>
   * 是否保留换行符
   * </pre>
   *
   * <code>bool preserve_newlines = 6;</code>
   * @return The preserveNewlines.
   */
  boolean getPreserveNewlines();

  /**
   * <pre>
   * 文本截取起始位置（可选，为空则从开头开始）
   * </pre>
   *
   * <code>optional int32 text_start_pos = 7;</code>
   * @return Whether the textStartPos field is set.
   */
  boolean hasTextStartPos();
  /**
   * <pre>
   * 文本截取起始位置（可选，为空则从开头开始）
   * </pre>
   *
   * <code>optional int32 text_start_pos = 7;</code>
   * @return The textStartPos.
   */
  int getTextStartPos();

  /**
   * <pre>
   * 文本截取结束位置（可选，为空则到结尾结束）
   * </pre>
   *
   * <code>optional int32 text_end_pos = 8;</code>
   * @return Whether the textEndPos field is set.
   */
  boolean hasTextEndPos();
  /**
   * <pre>
   * 文本截取结束位置（可选，为空则到结尾结束）
   * </pre>
   *
   * <code>optional int32 text_end_pos = 8;</code>
   * @return The textEndPos.
   */
  int getTextEndPos();
}
