// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_viewer.proto

package com.rpc.service.web.viewer.selectolax;

/**
 * <pre>
 * 浏览请求
 * </pre>
 *
 * Protobuf type {@code com.rpc.service.web.viewer.selectolax.ViewRequest}
 */
public final class ViewRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.rpc.service.web.viewer.selectolax.ViewRequest)
    ViewRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ViewRequest.newBuilder() to construct.
  private ViewRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ViewRequest() {
    url_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ViewRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetCustomHeaders();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rpc.service.web.viewer.selectolax.ViewRequest.class, com.rpc.service.web.viewer.selectolax.ViewRequest.Builder.class);
  }

  private int bitField0_;
  public static final int URL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object url_ = "";
  /**
   * <pre>
   * 要浏览的网页URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 要浏览的网页URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEOUT_SECONDS_FIELD_NUMBER = 2;
  private int timeoutSeconds_ = 0;
  /**
   * <pre>
   * 请求超时时间（秒），默认15秒
   * </pre>
   *
   * <code>int32 timeout_seconds = 2;</code>
   * @return The timeoutSeconds.
   */
  @java.lang.Override
  public int getTimeoutSeconds() {
    return timeoutSeconds_;
  }

  public static final int CUSTOM_HEADERS_FIELD_NUMBER = 3;
  private static final class CustomHeadersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_CustomHeadersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> customHeaders_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetCustomHeaders() {
    if (customHeaders_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CustomHeadersDefaultEntryHolder.defaultEntry);
    }
    return customHeaders_;
  }
  public int getCustomHeadersCount() {
    return internalGetCustomHeaders().getMap().size();
  }
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  @java.lang.Override
  public boolean containsCustomHeaders(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetCustomHeaders().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCustomHeadersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getCustomHeaders() {
    return getCustomHeadersMap();
  }
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getCustomHeadersMap() {
    return internalGetCustomHeaders().getMap();
  }
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getCustomHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetCustomHeaders().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  @java.lang.Override
  public java.lang.String getCustomHeadersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetCustomHeaders().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int INCLUDE_LINKS_FIELD_NUMBER = 4;
  private boolean includeLinks_ = false;
  /**
   * <pre>
   * 是否包含链接
   * </pre>
   *
   * <code>bool include_links = 4;</code>
   * @return The includeLinks.
   */
  @java.lang.Override
  public boolean getIncludeLinks() {
    return includeLinks_;
  }

  public static final int INCLUDE_IMAGES_FIELD_NUMBER = 5;
  private boolean includeImages_ = false;
  /**
   * <pre>
   * 是否包含图片信息
   * </pre>
   *
   * <code>bool include_images = 5;</code>
   * @return The includeImages.
   */
  @java.lang.Override
  public boolean getIncludeImages() {
    return includeImages_;
  }

  public static final int PRESERVE_NEWLINES_FIELD_NUMBER = 6;
  private boolean preserveNewlines_ = false;
  /**
   * <pre>
   * 是否保留换行符
   * </pre>
   *
   * <code>bool preserve_newlines = 6;</code>
   * @return The preserveNewlines.
   */
  @java.lang.Override
  public boolean getPreserveNewlines() {
    return preserveNewlines_;
  }

  public static final int TEXT_START_POS_FIELD_NUMBER = 7;
  private int textStartPos_ = 0;
  /**
   * <pre>
   * 文本截取起始位置（可选，为空则从开头开始）
   * </pre>
   *
   * <code>optional int32 text_start_pos = 7;</code>
   * @return Whether the textStartPos field is set.
   */
  @java.lang.Override
  public boolean hasTextStartPos() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 文本截取起始位置（可选，为空则从开头开始）
   * </pre>
   *
   * <code>optional int32 text_start_pos = 7;</code>
   * @return The textStartPos.
   */
  @java.lang.Override
  public int getTextStartPos() {
    return textStartPos_;
  }

  public static final int TEXT_END_POS_FIELD_NUMBER = 8;
  private int textEndPos_ = 0;
  /**
   * <pre>
   * 文本截取结束位置（可选，为空则到结尾结束）
   * </pre>
   *
   * <code>optional int32 text_end_pos = 8;</code>
   * @return Whether the textEndPos field is set.
   */
  @java.lang.Override
  public boolean hasTextEndPos() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 文本截取结束位置（可选，为空则到结尾结束）
   * </pre>
   *
   * <code>optional int32 text_end_pos = 8;</code>
   * @return The textEndPos.
   */
  @java.lang.Override
  public int getTextEndPos() {
    return textEndPos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
    }
    if (timeoutSeconds_ != 0) {
      output.writeInt32(2, timeoutSeconds_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetCustomHeaders(),
        CustomHeadersDefaultEntryHolder.defaultEntry,
        3);
    if (includeLinks_ != false) {
      output.writeBool(4, includeLinks_);
    }
    if (includeImages_ != false) {
      output.writeBool(5, includeImages_);
    }
    if (preserveNewlines_ != false) {
      output.writeBool(6, preserveNewlines_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(7, textStartPos_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(8, textEndPos_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
    }
    if (timeoutSeconds_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, timeoutSeconds_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetCustomHeaders().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      customHeaders__ = CustomHeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, customHeaders__);
    }
    if (includeLinks_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, includeLinks_);
    }
    if (includeImages_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, includeImages_);
    }
    if (preserveNewlines_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, preserveNewlines_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, textStartPos_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, textEndPos_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rpc.service.web.viewer.selectolax.ViewRequest)) {
      return super.equals(obj);
    }
    com.rpc.service.web.viewer.selectolax.ViewRequest other = (com.rpc.service.web.viewer.selectolax.ViewRequest) obj;

    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (getTimeoutSeconds()
        != other.getTimeoutSeconds()) return false;
    if (!internalGetCustomHeaders().equals(
        other.internalGetCustomHeaders())) return false;
    if (getIncludeLinks()
        != other.getIncludeLinks()) return false;
    if (getIncludeImages()
        != other.getIncludeImages()) return false;
    if (getPreserveNewlines()
        != other.getPreserveNewlines()) return false;
    if (hasTextStartPos() != other.hasTextStartPos()) return false;
    if (hasTextStartPos()) {
      if (getTextStartPos()
          != other.getTextStartPos()) return false;
    }
    if (hasTextEndPos() != other.hasTextEndPos()) return false;
    if (hasTextEndPos()) {
      if (getTextEndPos()
          != other.getTextEndPos()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (37 * hash) + TIMEOUT_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getTimeoutSeconds();
    if (!internalGetCustomHeaders().getMap().isEmpty()) {
      hash = (37 * hash) + CUSTOM_HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCustomHeaders().hashCode();
    }
    hash = (37 * hash) + INCLUDE_LINKS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludeLinks());
    hash = (37 * hash) + INCLUDE_IMAGES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludeImages());
    hash = (37 * hash) + PRESERVE_NEWLINES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPreserveNewlines());
    if (hasTextStartPos()) {
      hash = (37 * hash) + TEXT_START_POS_FIELD_NUMBER;
      hash = (53 * hash) + getTextStartPos();
    }
    if (hasTextEndPos()) {
      hash = (37 * hash) + TEXT_END_POS_FIELD_NUMBER;
      hash = (53 * hash) + getTextEndPos();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.viewer.selectolax.ViewRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rpc.service.web.viewer.selectolax.ViewRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 浏览请求
   * </pre>
   *
   * Protobuf type {@code com.rpc.service.web.viewer.selectolax.ViewRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.rpc.service.web.viewer.selectolax.ViewRequest)
      com.rpc.service.web.viewer.selectolax.ViewRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetCustomHeaders();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableCustomHeaders();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rpc.service.web.viewer.selectolax.ViewRequest.class, com.rpc.service.web.viewer.selectolax.ViewRequest.Builder.class);
    }

    // Construct using com.rpc.service.web.viewer.selectolax.ViewRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      url_ = "";
      timeoutSeconds_ = 0;
      internalGetMutableCustomHeaders().clear();
      includeLinks_ = false;
      includeImages_ = false;
      preserveNewlines_ = false;
      textStartPos_ = 0;
      textEndPos_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rpc.service.web.viewer.selectolax.SelectolaxProto.internal_static_com_rpc_service_web_viewer_selectolax_ViewRequest_descriptor;
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.selectolax.ViewRequest getDefaultInstanceForType() {
      return com.rpc.service.web.viewer.selectolax.ViewRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.selectolax.ViewRequest build() {
      com.rpc.service.web.viewer.selectolax.ViewRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.selectolax.ViewRequest buildPartial() {
      com.rpc.service.web.viewer.selectolax.ViewRequest result = new com.rpc.service.web.viewer.selectolax.ViewRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rpc.service.web.viewer.selectolax.ViewRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.url_ = url_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timeoutSeconds_ = timeoutSeconds_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.customHeaders_ = internalGetCustomHeaders();
        result.customHeaders_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.includeLinks_ = includeLinks_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.includeImages_ = includeImages_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.preserveNewlines_ = preserveNewlines_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.textStartPos_ = textStartPos_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.textEndPos_ = textEndPos_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rpc.service.web.viewer.selectolax.ViewRequest) {
        return mergeFrom((com.rpc.service.web.viewer.selectolax.ViewRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rpc.service.web.viewer.selectolax.ViewRequest other) {
      if (other == com.rpc.service.web.viewer.selectolax.ViewRequest.getDefaultInstance()) return this;
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTimeoutSeconds() != 0) {
        setTimeoutSeconds(other.getTimeoutSeconds());
      }
      internalGetMutableCustomHeaders().mergeFrom(
          other.internalGetCustomHeaders());
      bitField0_ |= 0x00000004;
      if (other.getIncludeLinks() != false) {
        setIncludeLinks(other.getIncludeLinks());
      }
      if (other.getIncludeImages() != false) {
        setIncludeImages(other.getIncludeImages());
      }
      if (other.getPreserveNewlines() != false) {
        setPreserveNewlines(other.getPreserveNewlines());
      }
      if (other.hasTextStartPos()) {
        setTextStartPos(other.getTextStartPos());
      }
      if (other.hasTextEndPos()) {
        setTextEndPos(other.getTextEndPos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              url_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              timeoutSeconds_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              customHeaders__ = input.readMessage(
                  CustomHeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableCustomHeaders().getMutableMap().put(
                  customHeaders__.getKey(), customHeaders__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              includeLinks_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              includeImages_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              preserveNewlines_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              textStartPos_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              textEndPos_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object url_ = "";
    /**
     * <pre>
     * 要浏览的网页URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 要浏览的网页URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 要浏览的网页URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要浏览的网页URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      url_ = getDefaultInstance().getUrl();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要浏览的网页URL
     * </pre>
     *
     * <code>string url = 1;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int timeoutSeconds_ ;
    /**
     * <pre>
     * 请求超时时间（秒），默认15秒
     * </pre>
     *
     * <code>int32 timeout_seconds = 2;</code>
     * @return The timeoutSeconds.
     */
    @java.lang.Override
    public int getTimeoutSeconds() {
      return timeoutSeconds_;
    }
    /**
     * <pre>
     * 请求超时时间（秒），默认15秒
     * </pre>
     *
     * <code>int32 timeout_seconds = 2;</code>
     * @param value The timeoutSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setTimeoutSeconds(int value) {

      timeoutSeconds_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求超时时间（秒），默认15秒
     * </pre>
     *
     * <code>int32 timeout_seconds = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeoutSeconds() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timeoutSeconds_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> customHeaders_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetCustomHeaders() {
      if (customHeaders_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CustomHeadersDefaultEntryHolder.defaultEntry);
      }
      return customHeaders_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableCustomHeaders() {
      if (customHeaders_ == null) {
        customHeaders_ = com.google.protobuf.MapField.newMapField(
            CustomHeadersDefaultEntryHolder.defaultEntry);
      }
      if (!customHeaders_.isMutable()) {
        customHeaders_ = customHeaders_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return customHeaders_;
    }
    public int getCustomHeadersCount() {
      return internalGetCustomHeaders().getMap().size();
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    @java.lang.Override
    public boolean containsCustomHeaders(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetCustomHeaders().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCustomHeadersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getCustomHeaders() {
      return getCustomHeadersMap();
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getCustomHeadersMap() {
      return internalGetCustomHeaders().getMap();
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getCustomHeadersOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetCustomHeaders().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getCustomHeadersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetCustomHeaders().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearCustomHeaders() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableCustomHeaders().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    public Builder removeCustomHeaders(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableCustomHeaders().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableCustomHeaders() {
      bitField0_ |= 0x00000004;
      return internalGetMutableCustomHeaders().getMutableMap();
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    public Builder putCustomHeaders(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableCustomHeaders().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    public Builder putAllCustomHeaders(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableCustomHeaders().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }

    private boolean includeLinks_ ;
    /**
     * <pre>
     * 是否包含链接
     * </pre>
     *
     * <code>bool include_links = 4;</code>
     * @return The includeLinks.
     */
    @java.lang.Override
    public boolean getIncludeLinks() {
      return includeLinks_;
    }
    /**
     * <pre>
     * 是否包含链接
     * </pre>
     *
     * <code>bool include_links = 4;</code>
     * @param value The includeLinks to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeLinks(boolean value) {

      includeLinks_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否包含链接
     * </pre>
     *
     * <code>bool include_links = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeLinks() {
      bitField0_ = (bitField0_ & ~0x00000008);
      includeLinks_ = false;
      onChanged();
      return this;
    }

    private boolean includeImages_ ;
    /**
     * <pre>
     * 是否包含图片信息
     * </pre>
     *
     * <code>bool include_images = 5;</code>
     * @return The includeImages.
     */
    @java.lang.Override
    public boolean getIncludeImages() {
      return includeImages_;
    }
    /**
     * <pre>
     * 是否包含图片信息
     * </pre>
     *
     * <code>bool include_images = 5;</code>
     * @param value The includeImages to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeImages(boolean value) {

      includeImages_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否包含图片信息
     * </pre>
     *
     * <code>bool include_images = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeImages() {
      bitField0_ = (bitField0_ & ~0x00000010);
      includeImages_ = false;
      onChanged();
      return this;
    }

    private boolean preserveNewlines_ ;
    /**
     * <pre>
     * 是否保留换行符
     * </pre>
     *
     * <code>bool preserve_newlines = 6;</code>
     * @return The preserveNewlines.
     */
    @java.lang.Override
    public boolean getPreserveNewlines() {
      return preserveNewlines_;
    }
    /**
     * <pre>
     * 是否保留换行符
     * </pre>
     *
     * <code>bool preserve_newlines = 6;</code>
     * @param value The preserveNewlines to set.
     * @return This builder for chaining.
     */
    public Builder setPreserveNewlines(boolean value) {

      preserveNewlines_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否保留换行符
     * </pre>
     *
     * <code>bool preserve_newlines = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreserveNewlines() {
      bitField0_ = (bitField0_ & ~0x00000020);
      preserveNewlines_ = false;
      onChanged();
      return this;
    }

    private int textStartPos_ ;
    /**
     * <pre>
     * 文本截取起始位置（可选，为空则从开头开始）
     * </pre>
     *
     * <code>optional int32 text_start_pos = 7;</code>
     * @return Whether the textStartPos field is set.
     */
    @java.lang.Override
    public boolean hasTextStartPos() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 文本截取起始位置（可选，为空则从开头开始）
     * </pre>
     *
     * <code>optional int32 text_start_pos = 7;</code>
     * @return The textStartPos.
     */
    @java.lang.Override
    public int getTextStartPos() {
      return textStartPos_;
    }
    /**
     * <pre>
     * 文本截取起始位置（可选，为空则从开头开始）
     * </pre>
     *
     * <code>optional int32 text_start_pos = 7;</code>
     * @param value The textStartPos to set.
     * @return This builder for chaining.
     */
    public Builder setTextStartPos(int value) {

      textStartPos_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本截取起始位置（可选，为空则从开头开始）
     * </pre>
     *
     * <code>optional int32 text_start_pos = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextStartPos() {
      bitField0_ = (bitField0_ & ~0x00000040);
      textStartPos_ = 0;
      onChanged();
      return this;
    }

    private int textEndPos_ ;
    /**
     * <pre>
     * 文本截取结束位置（可选，为空则到结尾结束）
     * </pre>
     *
     * <code>optional int32 text_end_pos = 8;</code>
     * @return Whether the textEndPos field is set.
     */
    @java.lang.Override
    public boolean hasTextEndPos() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 文本截取结束位置（可选，为空则到结尾结束）
     * </pre>
     *
     * <code>optional int32 text_end_pos = 8;</code>
     * @return The textEndPos.
     */
    @java.lang.Override
    public int getTextEndPos() {
      return textEndPos_;
    }
    /**
     * <pre>
     * 文本截取结束位置（可选，为空则到结尾结束）
     * </pre>
     *
     * <code>optional int32 text_end_pos = 8;</code>
     * @param value The textEndPos to set.
     * @return This builder for chaining.
     */
    public Builder setTextEndPos(int value) {

      textEndPos_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本截取结束位置（可选，为空则到结尾结束）
     * </pre>
     *
     * <code>optional int32 text_end_pos = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextEndPos() {
      bitField0_ = (bitField0_ & ~0x00000080);
      textEndPos_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.rpc.service.web.viewer.selectolax.ViewRequest)
  }

  // @@protoc_insertion_point(class_scope:com.rpc.service.web.viewer.selectolax.ViewRequest)
  private static final com.rpc.service.web.viewer.selectolax.ViewRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rpc.service.web.viewer.selectolax.ViewRequest();
  }

  public static com.rpc.service.web.viewer.selectolax.ViewRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ViewRequest>
      PARSER = new com.google.protobuf.AbstractParser<ViewRequest>() {
    @java.lang.Override
    public ViewRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ViewRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ViewRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rpc.service.web.viewer.selectolax.ViewRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

