// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_viewer.proto

package com.rpc.service.web.viewer.selectolax;

public interface ViewResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rpc.service.web.viewer.selectolax.ViewResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 原始URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * 原始URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * 页面标题
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * 页面标题
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 提取的文本内容
   * </pre>
   *
   * <code>string text_content = 3;</code>
   * @return The textContent.
   */
  java.lang.String getTextContent();
  /**
   * <pre>
   * 提取的文本内容
   * </pre>
   *
   * <code>string text_content = 3;</code>
   * @return The bytes for textContent.
   */
  com.google.protobuf.ByteString
      getTextContentBytes();

  /**
   * <pre>
   * 页面中的链接
   * </pre>
   *
   * <code>repeated string links = 4;</code>
   * @return A list containing the links.
   */
  java.util.List<java.lang.String>
      getLinksList();
  /**
   * <pre>
   * 页面中的链接
   * </pre>
   *
   * <code>repeated string links = 4;</code>
   * @return The count of links.
   */
  int getLinksCount();
  /**
   * <pre>
   * 页面中的链接
   * </pre>
   *
   * <code>repeated string links = 4;</code>
   * @param index The index of the element to return.
   * @return The links at the given index.
   */
  java.lang.String getLinks(int index);
  /**
   * <pre>
   * 页面中的链接
   * </pre>
   *
   * <code>repeated string links = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the links at the given index.
   */
  com.google.protobuf.ByteString
      getLinksBytes(int index);

  /**
   * <pre>
   * 页面中的图片URL
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @return A list containing the images.
   */
  java.util.List<java.lang.String>
      getImagesList();
  /**
   * <pre>
   * 页面中的图片URL
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @return The count of images.
   */
  int getImagesCount();
  /**
   * <pre>
   * 页面中的图片URL
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @param index The index of the element to return.
   * @return The images at the given index.
   */
  java.lang.String getImages(int index);
  /**
   * <pre>
   * 页面中的图片URL
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the images at the given index.
   */
  com.google.protobuf.ByteString
      getImagesBytes(int index);

  /**
   * <pre>
   * HTTP状态码
   * </pre>
   *
   * <code>int32 status_code = 6;</code>
   * @return The statusCode.
   */
  int getStatusCode();

  /**
   * <pre>
   * 浏览时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
   * @return Whether the viewedAt field is set.
   */
  boolean hasViewedAt();
  /**
   * <pre>
   * 浏览时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
   * @return The viewedAt.
   */
  com.google.protobuf.Timestamp getViewedAt();
  /**
   * <pre>
   * 浏览时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp viewed_at = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getViewedAtOrBuilder();

  /**
   * <pre>
   * 错误信息（如果有）
   * </pre>
   *
   * <code>string error_message = 8;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   * 错误信息（如果有）
   * </pre>
   *
   * <code>string error_message = 8;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * 处理时间（秒）
   * </pre>
   *
   * <code>double processing_time = 9;</code>
   * @return The processingTime.
   */
  double getProcessingTime();
}
