spring:
  application:
    name: MediAssist
  profiles:
    active: dev
  
  # MySQL数据库配置
  datasource:
    url: ${dev.db.url}
    username: ${dev.db.username}
    password: ${dev.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
    # Druid 连接池配置
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        allow: 127.0.0.1
        login-username: admin
        login-password: 123456
 
  # MongoDB配置
  data:
    redis:
      host: ${dev.redis.host}
      port: 6379
      password: ${dev.redis.password}
      database: 1
      # Redis连接池配置
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
          max-wait: -1ms
    mongodb:
      # 服务器地址和端口
      host: ${dev.mongo.host}
      port: ${dev.mongo.port}
      # 数据库名称
      database: ${dev.mongo.database}
      # 认证信息（如果需要）
      username: ${dev.mongo.username:}
      password: ${dev.mongo.password:}
      # 认证数据库（通常是admin）
      authentication-database: ${dev.mongo.auth-db:admin}
      # 连接选项
      options:
        # 连接超时时间（毫秒）
        connect-timeout: 10000
        # Socket超时时间（毫秒）
        socket-timeout: 30000
        # 服务器选择超时时间（毫秒）
        server-selection-timeout: 30000
        # 最大等待时间（毫秒）
        max-wait-time: 60000
        # 连接池最大连接数
        max-connection-pool-size: 100
        # 连接池最小连接数
        min-connection-pool-size: 5
        # 连接空闲时间（毫秒）
        max-connection-idle-time: 60000
        # 连接生存时间（毫秒）
        max-connection-life-time: 300000
        # 启用SSL（如果服务器支持）
        ssl-enabled: false
        # 是否验证SSL证书
        ssl-invalid-host-name-allowed: true


langchain4j:
  open-ai:
    chat-model:
      base-url: ${dev.openai.base-url}
      api-key: ${dev.openai.api-key}
      model-name: 'gpt-4o-mini'
#      model-name: 'gpt-4o-2024-11-20'
      temperature: 0.2
      log-requests: true
      log-responses: true
      # 网络超时配置（解决Connection reset问题）
      timeout: 60s           # 总超时时间60秒
      connect-timeout: 30s   # 连接超时30秒  
      read-timeout: 45s      # 读取超时45秒
      write-timeout: 30s     # 写入超时30秒
      # 重试配置
      max-retries: 3         # 最大重试3次
      # 调用频率限制
      max-requests-per-minute: 30
    streaming-chat-model:
      base-url: ${dev.openai.base-url}
      api-key: ${dev.openai.api-key}
      model-name: 'gpt-4o-mini'
      temperature: 0.2
      log-requests: true
      log-responses: true
      # 流式模型的超时配置
      timeout: 120s          # 流式响应需要更长时间
      connect-timeout: 30s   
      read-timeout: 90s      # 流式读取超时90秒
      write-timeout: 30s
      max-retries: 3

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aiassist.mediassist.dto.entity
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 显示SQL日志

# Weaviate向量数据库配置
weaviate:
  host: ${dev.weaviate.host}
  port: ${dev.weaviate.port}
  scheme: ${dev.weaviate.scheme}
  collection-name: ${dev.weaviate.collection}
  timeout: ${dev.weaviate.timeout}  # 连接超时时间(ms)

# 嵌入服务配置
embedding:
  base-url: ${dev.embedding.base-url}
  api-key: ${dev.embedding.api-key}
  model-name: text-embedding-3-small
  batch-size: 10  # 批量处理大小
  timeout: 30000   # 请求超时时间(ms)

# 聊天记忆配置
chat:
  mongodb:
    # 是否启用MongoDB持久化存储 - 重新启用用于诊断
    enable: true
  langchain:
    # 框架自动执行的窗口大小，设置为较大值，使其无效，完全由memory.max-size控制。
    max-size: 10
  memory:
    # 最大记忆消息窗口大小，消息淘汰的基准
    max-size: 6
  cache:
    expire-hours: 2        # 缓存过期时间（小时）
    # 缓存中的消息数量，比 记忆消息窗口 多记录一个系统提示词，所以大1
    max-size: 7

logging:
  level:
    com:
      aiassist:
        mediassist: INFO
#          tools: INFO