// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_grpc.proto

package com.rpc.service.web.viewer.gne;

/**
 * <pre>
 * 批量返回的响应格式
 * </pre>
 *
 * Protobuf type {@code com.rpc.service.web.viewer.gne.ContentListResponse}
 */
public final class ContentListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.rpc.service.web.viewer.gne.ContentListResponse)
    ContentListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContentListResponse.newBuilder() to construct.
  private ContentListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContentListResponse() {
    contents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContentListResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rpc.service.web.viewer.gne.ContentListResponse.class, com.rpc.service.web.viewer.gne.ContentListResponse.Builder.class);
  }

  public static final int CONTENTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.rpc.service.web.viewer.gne.Content> contents_;
  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.rpc.service.web.viewer.gne.Content> getContentsList() {
    return contents_;
  }
  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.rpc.service.web.viewer.gne.ContentOrBuilder> 
      getContentsOrBuilderList() {
    return contents_;
  }
  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  @java.lang.Override
  public int getContentsCount() {
    return contents_.size();
  }
  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  @java.lang.Override
  public com.rpc.service.web.viewer.gne.Content getContents(int index) {
    return contents_.get(index);
  }
  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  @java.lang.Override
  public com.rpc.service.web.viewer.gne.ContentOrBuilder getContentsOrBuilder(
      int index) {
    return contents_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < contents_.size(); i++) {
      output.writeMessage(1, contents_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < contents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, contents_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rpc.service.web.viewer.gne.ContentListResponse)) {
      return super.equals(obj);
    }
    com.rpc.service.web.viewer.gne.ContentListResponse other = (com.rpc.service.web.viewer.gne.ContentListResponse) obj;

    if (!getContentsList()
        .equals(other.getContentsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getContentsCount() > 0) {
      hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
      hash = (53 * hash) + getContentsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rpc.service.web.viewer.gne.ContentListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rpc.service.web.viewer.gne.ContentListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.viewer.gne.ContentListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rpc.service.web.viewer.gne.ContentListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 批量返回的响应格式
   * </pre>
   *
   * Protobuf type {@code com.rpc.service.web.viewer.gne.ContentListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.rpc.service.web.viewer.gne.ContentListResponse)
      com.rpc.service.web.viewer.gne.ContentListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rpc.service.web.viewer.gne.ContentListResponse.class, com.rpc.service.web.viewer.gne.ContentListResponse.Builder.class);
    }

    // Construct using com.rpc.service.web.viewer.gne.ContentListResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (contentsBuilder_ == null) {
        contents_ = java.util.Collections.emptyList();
      } else {
        contents_ = null;
        contentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_descriptor;
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.gne.ContentListResponse getDefaultInstanceForType() {
      return com.rpc.service.web.viewer.gne.ContentListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.gne.ContentListResponse build() {
      com.rpc.service.web.viewer.gne.ContentListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.gne.ContentListResponse buildPartial() {
      com.rpc.service.web.viewer.gne.ContentListResponse result = new com.rpc.service.web.viewer.gne.ContentListResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.rpc.service.web.viewer.gne.ContentListResponse result) {
      if (contentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          contents_ = java.util.Collections.unmodifiableList(contents_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.contents_ = contents_;
      } else {
        result.contents_ = contentsBuilder_.build();
      }
    }

    private void buildPartial0(com.rpc.service.web.viewer.gne.ContentListResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rpc.service.web.viewer.gne.ContentListResponse) {
        return mergeFrom((com.rpc.service.web.viewer.gne.ContentListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rpc.service.web.viewer.gne.ContentListResponse other) {
      if (other == com.rpc.service.web.viewer.gne.ContentListResponse.getDefaultInstance()) return this;
      if (contentsBuilder_ == null) {
        if (!other.contents_.isEmpty()) {
          if (contents_.isEmpty()) {
            contents_ = other.contents_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureContentsIsMutable();
            contents_.addAll(other.contents_);
          }
          onChanged();
        }
      } else {
        if (!other.contents_.isEmpty()) {
          if (contentsBuilder_.isEmpty()) {
            contentsBuilder_.dispose();
            contentsBuilder_ = null;
            contents_ = other.contents_;
            bitField0_ = (bitField0_ & ~0x00000001);
            contentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getContentsFieldBuilder() : null;
          } else {
            contentsBuilder_.addAllMessages(other.contents_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.rpc.service.web.viewer.gne.Content m =
                  input.readMessage(
                      com.rpc.service.web.viewer.gne.Content.parser(),
                      extensionRegistry);
              if (contentsBuilder_ == null) {
                ensureContentsIsMutable();
                contents_.add(m);
              } else {
                contentsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.rpc.service.web.viewer.gne.Content> contents_ =
      java.util.Collections.emptyList();
    private void ensureContentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        contents_ = new java.util.ArrayList<com.rpc.service.web.viewer.gne.Content>(contents_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.rpc.service.web.viewer.gne.Content, com.rpc.service.web.viewer.gne.Content.Builder, com.rpc.service.web.viewer.gne.ContentOrBuilder> contentsBuilder_;

    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public java.util.List<com.rpc.service.web.viewer.gne.Content> getContentsList() {
      if (contentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(contents_);
      } else {
        return contentsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public int getContentsCount() {
      if (contentsBuilder_ == null) {
        return contents_.size();
      } else {
        return contentsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public com.rpc.service.web.viewer.gne.Content getContents(int index) {
      if (contentsBuilder_ == null) {
        return contents_.get(index);
      } else {
        return contentsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public Builder setContents(
        int index, com.rpc.service.web.viewer.gne.Content value) {
      if (contentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentsIsMutable();
        contents_.set(index, value);
        onChanged();
      } else {
        contentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public Builder setContents(
        int index, com.rpc.service.web.viewer.gne.Content.Builder builderForValue) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        contents_.set(index, builderForValue.build());
        onChanged();
      } else {
        contentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public Builder addContents(com.rpc.service.web.viewer.gne.Content value) {
      if (contentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentsIsMutable();
        contents_.add(value);
        onChanged();
      } else {
        contentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public Builder addContents(
        int index, com.rpc.service.web.viewer.gne.Content value) {
      if (contentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentsIsMutable();
        contents_.add(index, value);
        onChanged();
      } else {
        contentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public Builder addContents(
        com.rpc.service.web.viewer.gne.Content.Builder builderForValue) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        contents_.add(builderForValue.build());
        onChanged();
      } else {
        contentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public Builder addContents(
        int index, com.rpc.service.web.viewer.gne.Content.Builder builderForValue) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        contents_.add(index, builderForValue.build());
        onChanged();
      } else {
        contentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public Builder addAllContents(
        java.lang.Iterable<? extends com.rpc.service.web.viewer.gne.Content> values) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contents_);
        onChanged();
      } else {
        contentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public Builder clearContents() {
      if (contentsBuilder_ == null) {
        contents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        contentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public Builder removeContents(int index) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        contents_.remove(index);
        onChanged();
      } else {
        contentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public com.rpc.service.web.viewer.gne.Content.Builder getContentsBuilder(
        int index) {
      return getContentsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public com.rpc.service.web.viewer.gne.ContentOrBuilder getContentsOrBuilder(
        int index) {
      if (contentsBuilder_ == null) {
        return contents_.get(index);  } else {
        return contentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public java.util.List<? extends com.rpc.service.web.viewer.gne.ContentOrBuilder> 
         getContentsOrBuilderList() {
      if (contentsBuilder_ != null) {
        return contentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(contents_);
      }
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public com.rpc.service.web.viewer.gne.Content.Builder addContentsBuilder() {
      return getContentsFieldBuilder().addBuilder(
          com.rpc.service.web.viewer.gne.Content.getDefaultInstance());
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public com.rpc.service.web.viewer.gne.Content.Builder addContentsBuilder(
        int index) {
      return getContentsFieldBuilder().addBuilder(
          index, com.rpc.service.web.viewer.gne.Content.getDefaultInstance());
    }
    /**
     * <pre>
     * 包含多个 Content 的列表
     * </pre>
     *
     * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
     */
    public java.util.List<com.rpc.service.web.viewer.gne.Content.Builder> 
         getContentsBuilderList() {
      return getContentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.rpc.service.web.viewer.gne.Content, com.rpc.service.web.viewer.gne.Content.Builder, com.rpc.service.web.viewer.gne.ContentOrBuilder> 
        getContentsFieldBuilder() {
      if (contentsBuilder_ == null) {
        contentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.rpc.service.web.viewer.gne.Content, com.rpc.service.web.viewer.gne.Content.Builder, com.rpc.service.web.viewer.gne.ContentOrBuilder>(
                contents_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        contents_ = null;
      }
      return contentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.rpc.service.web.viewer.gne.ContentListResponse)
  }

  // @@protoc_insertion_point(class_scope:com.rpc.service.web.viewer.gne.ContentListResponse)
  private static final com.rpc.service.web.viewer.gne.ContentListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rpc.service.web.viewer.gne.ContentListResponse();
  }

  public static com.rpc.service.web.viewer.gne.ContentListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContentListResponse>
      PARSER = new com.google.protobuf.AbstractParser<ContentListResponse>() {
    @java.lang.Override
    public ContentListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContentListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContentListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rpc.service.web.viewer.gne.ContentListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

