// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_grpc.proto

package com.rpc.service.web.viewer.gne;

public interface ContentListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rpc.service.web.viewer.gne.ContentListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  java.util.List<com.rpc.service.web.viewer.gne.Content> 
      getContentsList();
  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  com.rpc.service.web.viewer.gne.Content getContents(int index);
  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  int getContentsCount();
  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  java.util.List<? extends com.rpc.service.web.viewer.gne.ContentOrBuilder> 
      getContentsOrBuilderList();
  /**
   * <pre>
   * 包含多个 Content 的列表
   * </pre>
   *
   * <code>repeated .com.rpc.service.web.viewer.gne.Content contents = 1;</code>
   */
  com.rpc.service.web.viewer.gne.ContentOrBuilder getContentsOrBuilder(
      int index);
}
