// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_grpc.proto

package com.rpc.service.web.viewer.gne;

public interface ContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rpc.service.web.viewer.gne.Content)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 字符串字段，表示标题
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * 字符串字段，表示标题
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 字符串字段，表示作者
   * </pre>
   *
   * <code>string author = 2;</code>
   * @return The author.
   */
  java.lang.String getAuthor();
  /**
   * <pre>
   * 字符串字段，表示作者
   * </pre>
   *
   * <code>string author = 2;</code>
   * @return The bytes for author.
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <pre>
   * 字符串字段，表示发布时间
   * </pre>
   *
   * <code>string publish_time = 3;</code>
   * @return The publishTime.
   */
  java.lang.String getPublishTime();
  /**
   * <pre>
   * 字符串字段，表示发布时间
   * </pre>
   *
   * <code>string publish_time = 3;</code>
   * @return The bytes for publishTime.
   */
  com.google.protobuf.ByteString
      getPublishTimeBytes();

  /**
   * <pre>
   * 字符串字段，表示正文
   * </pre>
   *
   * <code>string content = 4;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 字符串字段，表示正文
   * </pre>
   *
   * <code>string content = 4;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 字符串数组，存储多个图片链接
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @return A list containing the images.
   */
  java.util.List<java.lang.String>
      getImagesList();
  /**
   * <pre>
   * 字符串数组，存储多个图片链接
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @return The count of images.
   */
  int getImagesCount();
  /**
   * <pre>
   * 字符串数组，存储多个图片链接
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @param index The index of the element to return.
   * @return The images at the given index.
   */
  java.lang.String getImages(int index);
  /**
   * <pre>
   * 字符串数组，存储多个图片链接
   * </pre>
   *
   * <code>repeated string images = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the images at the given index.
   */
  com.google.protobuf.ByteString
      getImagesBytes(int index);

  /**
   * <pre>
   * 键值对类型（Map），存储元信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 6;</code>
   */
  int getMetaCount();
  /**
   * <pre>
   * 键值对类型（Map），存储元信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 6;</code>
   */
  boolean containsMeta(
      java.lang.String key);
  /**
   * Use {@link #getMetaMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMeta();
  /**
   * <pre>
   * 键值对类型（Map），存储元信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetaMap();
  /**
   * <pre>
   * 键值对类型（Map），存储元信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 6;</code>
   */
  /* nullable */
java.lang.String getMetaOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 键值对类型（Map），存储元信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 6;</code>
   */
  java.lang.String getMetaOrThrow(
      java.lang.String key);
}
