// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_grpc.proto

package com.rpc.service.web.viewer.gne;

public final class GNEProto {
  private GNEProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_viewer_gne_WebListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_viewer_gne_WebListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_viewer_gne_WebListRequest_CustomHeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_viewer_gne_WebListRequest_CustomHeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_viewer_gne_Content_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_viewer_gne_Content_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_viewer_gne_Content_MetaEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_viewer_gne_Content_MetaEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016web_grpc.proto\022\036com.rpc.service.web.vi" +
      "ewer.gne\"\310\001\n\016WebListRequest\022\014\n\004urls\030\001 \003(" +
      "\t\022\027\n\017timeout_seconds\030\002 \001(\005\022Y\n\016custom_hea" +
      "ders\030\003 \003(\0132A.com.rpc.service.web.viewer." +
      "gne.WebListRequest.CustomHeadersEntry\0324\n" +
      "\022CustomHeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\"\315\001\n\007Content\022\r\n\005title\030\001 \001(\t\022\016" +
      "\n\006author\030\002 \001(\t\022\024\n\014publish_time\030\003 \001(\t\022\017\n\007" +
      "content\030\004 \001(\t\022\016\n\006images\030\005 \003(\t\022?\n\004meta\030\006 " +
      "\003(\01321.com.rpc.service.web.viewer.gne.Con" +
      "tent.MetaEntry\032+\n\tMetaEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\001\"P\n\023ContentListRespon" +
      "se\0229\n\010contents\030\001 \003(\0132\'.com.rpc.service.w" +
      "eb.viewer.gne.Content2\204\001\n\021NewsViewerServ" +
      "ice\022o\n\010ViewPage\022..com.rpc.service.web.vi" +
      "ewer.gne.WebListRequest\0323.com.rpc.servic" +
      "e.web.viewer.gne.ContentListResponseB,\n\036" +
      "com.rpc.service.web.viewer.gneB\010GNEProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_rpc_service_web_viewer_gne_WebListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rpc_service_web_viewer_gne_WebListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_viewer_gne_WebListRequest_descriptor,
        new java.lang.String[] { "Urls", "TimeoutSeconds", "CustomHeaders", });
    internal_static_com_rpc_service_web_viewer_gne_WebListRequest_CustomHeadersEntry_descriptor =
      internal_static_com_rpc_service_web_viewer_gne_WebListRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_rpc_service_web_viewer_gne_WebListRequest_CustomHeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_viewer_gne_WebListRequest_CustomHeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_rpc_service_web_viewer_gne_Content_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_rpc_service_web_viewer_gne_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_viewer_gne_Content_descriptor,
        new java.lang.String[] { "Title", "Author", "PublishTime", "Content", "Images", "Meta", });
    internal_static_com_rpc_service_web_viewer_gne_Content_MetaEntry_descriptor =
      internal_static_com_rpc_service_web_viewer_gne_Content_descriptor.getNestedTypes().get(0);
    internal_static_com_rpc_service_web_viewer_gne_Content_MetaEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_viewer_gne_Content_MetaEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rpc_service_web_viewer_gne_ContentListResponse_descriptor,
        new java.lang.String[] { "Contents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
