// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_grpc.proto

package com.rpc.service.web.viewer.gne;

/**
 * Protobuf type {@code com.rpc.service.web.viewer.gne.WebListRequest}
 */
public final class WebListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.rpc.service.web.viewer.gne.WebListRequest)
    WebListRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WebListRequest.newBuilder() to construct.
  private WebListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WebListRequest() {
    urls_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WebListRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_WebListRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetCustomHeaders();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_WebListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rpc.service.web.viewer.gne.WebListRequest.class, com.rpc.service.web.viewer.gne.WebListRequest.Builder.class);
  }

  public static final int URLS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList urls_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string urls = 1;</code>
   * @return A list containing the urls.
   */
  public com.google.protobuf.ProtocolStringList
      getUrlsList() {
    return urls_;
  }
  /**
   * <code>repeated string urls = 1;</code>
   * @return The count of urls.
   */
  public int getUrlsCount() {
    return urls_.size();
  }
  /**
   * <code>repeated string urls = 1;</code>
   * @param index The index of the element to return.
   * @return The urls at the given index.
   */
  public java.lang.String getUrls(int index) {
    return urls_.get(index);
  }
  /**
   * <code>repeated string urls = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the urls at the given index.
   */
  public com.google.protobuf.ByteString
      getUrlsBytes(int index) {
    return urls_.getByteString(index);
  }

  public static final int TIMEOUT_SECONDS_FIELD_NUMBER = 2;
  private int timeoutSeconds_ = 0;
  /**
   * <pre>
   * 请求超时时间（秒）
   * </pre>
   *
   * <code>int32 timeout_seconds = 2;</code>
   * @return The timeoutSeconds.
   */
  @java.lang.Override
  public int getTimeoutSeconds() {
    return timeoutSeconds_;
  }

  public static final int CUSTOM_HEADERS_FIELD_NUMBER = 3;
  private static final class CustomHeadersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_WebListRequest_CustomHeadersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> customHeaders_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetCustomHeaders() {
    if (customHeaders_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CustomHeadersDefaultEntryHolder.defaultEntry);
    }
    return customHeaders_;
  }
  public int getCustomHeadersCount() {
    return internalGetCustomHeaders().getMap().size();
  }
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  @java.lang.Override
  public boolean containsCustomHeaders(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetCustomHeaders().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCustomHeadersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getCustomHeaders() {
    return getCustomHeadersMap();
  }
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getCustomHeadersMap() {
    return internalGetCustomHeaders().getMap();
  }
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getCustomHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetCustomHeaders().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  @java.lang.Override
  public java.lang.String getCustomHeadersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetCustomHeaders().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < urls_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, urls_.getRaw(i));
    }
    if (timeoutSeconds_ != 0) {
      output.writeInt32(2, timeoutSeconds_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetCustomHeaders(),
        CustomHeadersDefaultEntryHolder.defaultEntry,
        3);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < urls_.size(); i++) {
        dataSize += computeStringSizeNoTag(urls_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUrlsList().size();
    }
    if (timeoutSeconds_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, timeoutSeconds_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetCustomHeaders().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      customHeaders__ = CustomHeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, customHeaders__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rpc.service.web.viewer.gne.WebListRequest)) {
      return super.equals(obj);
    }
    com.rpc.service.web.viewer.gne.WebListRequest other = (com.rpc.service.web.viewer.gne.WebListRequest) obj;

    if (!getUrlsList()
        .equals(other.getUrlsList())) return false;
    if (getTimeoutSeconds()
        != other.getTimeoutSeconds()) return false;
    if (!internalGetCustomHeaders().equals(
        other.internalGetCustomHeaders())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUrlsCount() > 0) {
      hash = (37 * hash) + URLS_FIELD_NUMBER;
      hash = (53 * hash) + getUrlsList().hashCode();
    }
    hash = (37 * hash) + TIMEOUT_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getTimeoutSeconds();
    if (!internalGetCustomHeaders().getMap().isEmpty()) {
      hash = (37 * hash) + CUSTOM_HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCustomHeaders().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rpc.service.web.viewer.gne.WebListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rpc.service.web.viewer.gne.WebListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rpc.service.web.viewer.gne.WebListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rpc.service.web.viewer.gne.WebListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.rpc.service.web.viewer.gne.WebListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.rpc.service.web.viewer.gne.WebListRequest)
      com.rpc.service.web.viewer.gne.WebListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_WebListRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetCustomHeaders();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableCustomHeaders();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_WebListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rpc.service.web.viewer.gne.WebListRequest.class, com.rpc.service.web.viewer.gne.WebListRequest.Builder.class);
    }

    // Construct using com.rpc.service.web.viewer.gne.WebListRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      urls_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      timeoutSeconds_ = 0;
      internalGetMutableCustomHeaders().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rpc.service.web.viewer.gne.GNEProto.internal_static_com_rpc_service_web_viewer_gne_WebListRequest_descriptor;
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.gne.WebListRequest getDefaultInstanceForType() {
      return com.rpc.service.web.viewer.gne.WebListRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.gne.WebListRequest build() {
      com.rpc.service.web.viewer.gne.WebListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rpc.service.web.viewer.gne.WebListRequest buildPartial() {
      com.rpc.service.web.viewer.gne.WebListRequest result = new com.rpc.service.web.viewer.gne.WebListRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rpc.service.web.viewer.gne.WebListRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        urls_.makeImmutable();
        result.urls_ = urls_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timeoutSeconds_ = timeoutSeconds_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.customHeaders_ = internalGetCustomHeaders();
        result.customHeaders_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rpc.service.web.viewer.gne.WebListRequest) {
        return mergeFrom((com.rpc.service.web.viewer.gne.WebListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rpc.service.web.viewer.gne.WebListRequest other) {
      if (other == com.rpc.service.web.viewer.gne.WebListRequest.getDefaultInstance()) return this;
      if (!other.urls_.isEmpty()) {
        if (urls_.isEmpty()) {
          urls_ = other.urls_;
          bitField0_ |= 0x00000001;
        } else {
          ensureUrlsIsMutable();
          urls_.addAll(other.urls_);
        }
        onChanged();
      }
      if (other.getTimeoutSeconds() != 0) {
        setTimeoutSeconds(other.getTimeoutSeconds());
      }
      internalGetMutableCustomHeaders().mergeFrom(
          other.internalGetCustomHeaders());
      bitField0_ |= 0x00000004;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureUrlsIsMutable();
              urls_.add(s);
              break;
            } // case 10
            case 16: {
              timeoutSeconds_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              customHeaders__ = input.readMessage(
                  CustomHeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableCustomHeaders().getMutableMap().put(
                  customHeaders__.getKey(), customHeaders__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList urls_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureUrlsIsMutable() {
      if (!urls_.isModifiable()) {
        urls_ = new com.google.protobuf.LazyStringArrayList(urls_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string urls = 1;</code>
     * @return A list containing the urls.
     */
    public com.google.protobuf.ProtocolStringList
        getUrlsList() {
      urls_.makeImmutable();
      return urls_;
    }
    /**
     * <code>repeated string urls = 1;</code>
     * @return The count of urls.
     */
    public int getUrlsCount() {
      return urls_.size();
    }
    /**
     * <code>repeated string urls = 1;</code>
     * @param index The index of the element to return.
     * @return The urls at the given index.
     */
    public java.lang.String getUrls(int index) {
      return urls_.get(index);
    }
    /**
     * <code>repeated string urls = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the urls at the given index.
     */
    public com.google.protobuf.ByteString
        getUrlsBytes(int index) {
      return urls_.getByteString(index);
    }
    /**
     * <code>repeated string urls = 1;</code>
     * @param index The index to set the value at.
     * @param value The urls to set.
     * @return This builder for chaining.
     */
    public Builder setUrls(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUrlsIsMutable();
      urls_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string urls = 1;</code>
     * @param value The urls to add.
     * @return This builder for chaining.
     */
    public Builder addUrls(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUrlsIsMutable();
      urls_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string urls = 1;</code>
     * @param values The urls to add.
     * @return This builder for chaining.
     */
    public Builder addAllUrls(
        java.lang.Iterable<java.lang.String> values) {
      ensureUrlsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, urls_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string urls = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrls() {
      urls_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string urls = 1;</code>
     * @param value The bytes of the urls to add.
     * @return This builder for chaining.
     */
    public Builder addUrlsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureUrlsIsMutable();
      urls_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int timeoutSeconds_ ;
    /**
     * <pre>
     * 请求超时时间（秒）
     * </pre>
     *
     * <code>int32 timeout_seconds = 2;</code>
     * @return The timeoutSeconds.
     */
    @java.lang.Override
    public int getTimeoutSeconds() {
      return timeoutSeconds_;
    }
    /**
     * <pre>
     * 请求超时时间（秒）
     * </pre>
     *
     * <code>int32 timeout_seconds = 2;</code>
     * @param value The timeoutSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setTimeoutSeconds(int value) {

      timeoutSeconds_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求超时时间（秒）
     * </pre>
     *
     * <code>int32 timeout_seconds = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeoutSeconds() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timeoutSeconds_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> customHeaders_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetCustomHeaders() {
      if (customHeaders_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CustomHeadersDefaultEntryHolder.defaultEntry);
      }
      return customHeaders_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableCustomHeaders() {
      if (customHeaders_ == null) {
        customHeaders_ = com.google.protobuf.MapField.newMapField(
            CustomHeadersDefaultEntryHolder.defaultEntry);
      }
      if (!customHeaders_.isMutable()) {
        customHeaders_ = customHeaders_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return customHeaders_;
    }
    public int getCustomHeadersCount() {
      return internalGetCustomHeaders().getMap().size();
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    @java.lang.Override
    public boolean containsCustomHeaders(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetCustomHeaders().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCustomHeadersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getCustomHeaders() {
      return getCustomHeadersMap();
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getCustomHeadersMap() {
      return internalGetCustomHeaders().getMap();
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getCustomHeadersOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetCustomHeaders().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getCustomHeadersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetCustomHeaders().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearCustomHeaders() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableCustomHeaders().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    public Builder removeCustomHeaders(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableCustomHeaders().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableCustomHeaders() {
      bitField0_ |= 0x00000004;
      return internalGetMutableCustomHeaders().getMutableMap();
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    public Builder putCustomHeaders(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableCustomHeaders().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * 自定义请求头
     * </pre>
     *
     * <code>map&lt;string, string&gt; custom_headers = 3;</code>
     */
    public Builder putAllCustomHeaders(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableCustomHeaders().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.rpc.service.web.viewer.gne.WebListRequest)
  }

  // @@protoc_insertion_point(class_scope:com.rpc.service.web.viewer.gne.WebListRequest)
  private static final com.rpc.service.web.viewer.gne.WebListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rpc.service.web.viewer.gne.WebListRequest();
  }

  public static com.rpc.service.web.viewer.gne.WebListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WebListRequest>
      PARSER = new com.google.protobuf.AbstractParser<WebListRequest>() {
    @java.lang.Override
    public WebListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WebListRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WebListRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rpc.service.web.viewer.gne.WebListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

