// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_grpc.proto

package com.rpc.service.web.viewer.gne;

public interface WebListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rpc.service.web.viewer.gne.WebListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string urls = 1;</code>
   * @return A list containing the urls.
   */
  java.util.List<java.lang.String>
      getUrlsList();
  /**
   * <code>repeated string urls = 1;</code>
   * @return The count of urls.
   */
  int getUrlsCount();
  /**
   * <code>repeated string urls = 1;</code>
   * @param index The index of the element to return.
   * @return The urls at the given index.
   */
  java.lang.String getUrls(int index);
  /**
   * <code>repeated string urls = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the urls at the given index.
   */
  com.google.protobuf.ByteString
      getUrlsBytes(int index);

  /**
   * <pre>
   * 请求超时时间（秒）
   * </pre>
   *
   * <code>int32 timeout_seconds = 2;</code>
   * @return The timeoutSeconds.
   */
  int getTimeoutSeconds();

  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  int getCustomHeadersCount();
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  boolean containsCustomHeaders(
      java.lang.String key);
  /**
   * Use {@link #getCustomHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getCustomHeaders();
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getCustomHeadersMap();
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  /* nullable */
java.lang.String getCustomHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 自定义请求头
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 3;</code>
   */
  java.lang.String getCustomHeadersOrThrow(
      java.lang.String key);
}
